"""create canonical tenant schema

Revision ID: 3cd64c705778
Revises:
Create Date: 2026-07-27 20:46:40.649900

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3cd64c705778"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brokers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "broker_sources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("broker_id", sa.String(length=36), nullable=False),
        sa.Column(
            "tms_type",
            sa.Enum(
                "freightflow",
                "hauldesk",
                "brokeros",
                name="tms_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["broker_id"], ["brokers.id"], name="fk_broker_sources_broker", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("broker_id", "id", name="uq_broker_sources_broker_id_id"),
        sa.UniqueConstraint("broker_id", "tms_type", name="uq_broker_sources_broker_tms_type"),
    )
    op.create_table(
        "carriers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("broker_id", sa.String(length=36), nullable=False),
        sa.Column("broker_source_id", sa.String(length=36), nullable=False),
        sa.Column("source_carrier_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("mc_number", sa.String(length=32), nullable=True),
        sa.Column("dot_number", sa.String(length=32), nullable=True),
        sa.Column("phone_number", sa.String(length=64), nullable=True),
        sa.Column("home_city", sa.String(length=255), nullable=True),
        sa.Column("home_state", sa.String(length=2), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["broker_id", "broker_source_id"],
            ["broker_sources.broker_id", "broker_sources.id"],
            name="fk_carriers_source",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("broker_id", "id", name="uq_carriers_broker_id_id"),
        sa.UniqueConstraint(
            "broker_id", "broker_source_id", "id", name="uq_carriers_broker_source_id_id"
        ),
        sa.UniqueConstraint(
            "broker_source_id", "source_carrier_id", name="uq_carriers_source_carrier_id"
        ),
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("broker_id", sa.String(length=36), nullable=False),
        sa.Column("broker_source_id", sa.String(length=36), nullable=False),
        sa.Column("source_customer_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["broker_id", "broker_source_id"],
            ["broker_sources.broker_id", "broker_sources.id"],
            name="fk_customers_source",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("broker_id", "id", name="uq_customers_broker_id_id"),
        sa.UniqueConstraint(
            "broker_id", "broker_source_id", "id", name="uq_customers_broker_source_id_id"
        ),
        sa.UniqueConstraint(
            "broker_source_id", "source_customer_id", name="uq_customers_source_customer_id"
        ),
    )
    op.create_table(
        "ingestion_files",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("broker_id", sa.String(length=36), nullable=False),
        sa.Column("broker_source_id", sa.String(length=36), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "processing",
                "succeeded",
                "failed",
                name="ingestion_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(
            ["broker_id", "broker_source_id"],
            ["broker_sources.broker_id", "broker_sources.id"],
            name="fk_ingestion_files_source",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("broker_id", "id", name="uq_ingestion_files_broker_id_id"),
        sa.UniqueConstraint(
            "broker_source_id", "filename", name="uq_ingestion_files_source_filename"
        ),
    )
    op.create_table(
        "loads",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("broker_id", sa.String(length=36), nullable=False),
        sa.Column("broker_source_id", sa.String(length=36), nullable=False),
        sa.Column("source_load_id", sa.String(length=255), nullable=False),
        sa.Column("display_number", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "planned",
                "active",
                "covered",
                "in_transit",
                "delivered",
                "completed",
                name="load_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("customer_id", sa.String(length=36), nullable=False),
        sa.Column("carrier_id", sa.String(length=36), nullable=True),
        sa.Column(
            "equipment_type",
            sa.Enum(
                "dry_van",
                "reefer",
                "flatbed",
                "unknown",
                name="equipment_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("weight_lbs", sa.Numeric(precision=12, scale=1), nullable=True),
        sa.Column("distance_miles", sa.Numeric(precision=10, scale=1), nullable=True),
        sa.Column("customer_rate", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("carrier_rate", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("source_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("booked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["broker_id", "broker_source_id"],
            ["broker_sources.broker_id", "broker_sources.id"],
            name="fk_loads_source",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["broker_id", "broker_source_id", "carrier_id"],
            ["carriers.broker_id", "carriers.broker_source_id", "carriers.id"],
            name="fk_loads_carrier",
        ),
        sa.ForeignKeyConstraint(
            ["broker_id", "broker_source_id", "customer_id"],
            ["customers.broker_id", "customers.broker_source_id", "customers.id"],
            name="fk_loads_customer",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("broker_id", "id", name="uq_loads_broker_id_id"),
        sa.UniqueConstraint(
            "broker_id", "broker_source_id", "id", name="uq_loads_broker_source_id_id"
        ),
        sa.UniqueConstraint("broker_source_id", "source_load_id", name="uq_loads_source_load_id"),
    )
    op.create_table(
        "load_stops",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("broker_id", sa.String(length=36), nullable=False),
        sa.Column("load_id", sa.String(length=36), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column(
            "stop_type",
            sa.Enum(
                "pickup",
                "dropoff",
                "pickup_dropoff",
                name="stop_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("city", sa.String(length=255), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("postal_code", sa.String(length=16), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("scheduled_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scheduled_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_arrived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_departed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("sequence_number > 0", name="ck_load_stops_sequence_positive"),
        sa.ForeignKeyConstraint(
            ["broker_id", "load_id"],
            ["loads.broker_id", "loads.id"],
            name="fk_load_stops_load",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("broker_id", "id", name="uq_load_stops_broker_id_id"),
        sa.UniqueConstraint("load_id", "sequence_number", name="uq_load_stops_load_sequence"),
    )
    op.create_table(
        "load_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("broker_id", sa.String(length=36), nullable=False),
        sa.Column("load_id", sa.String(length=36), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_payload", sa.JSON(), nullable=False),
        sa.Column("normalized_snapshot", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["broker_id", "load_id"],
            ["loads.broker_id", "loads.id"],
            name="fk_load_versions_load",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("broker_id", "id", name="uq_load_versions_broker_id_id"),
        sa.UniqueConstraint("load_id", "version_number", name="uq_load_versions_load_version"),
    )
    op.create_table(
        "rate_line_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("broker_id", sa.String(length=36), nullable=False),
        sa.Column("broker_source_id", sa.String(length=36), nullable=False),
        sa.Column("load_id", sa.String(length=36), nullable=False),
        sa.Column("source_rate_id", sa.String(length=255), nullable=False),
        sa.Column(
            "side",
            sa.Enum("bill", "pay", name="rate_side", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("source_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["broker_id", "broker_source_id"],
            ["broker_sources.broker_id", "broker_sources.id"],
            name="fk_rate_line_items_source",
        ),
        sa.ForeignKeyConstraint(
            ["broker_id", "broker_source_id", "load_id"],
            ["loads.broker_id", "loads.broker_source_id", "loads.id"],
            name="fk_rate_line_items_load",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("broker_id", "id", name="uq_rate_line_items_broker_id_id"),
        sa.UniqueConstraint(
            "broker_source_id", "source_rate_id", name="uq_rate_line_items_source_rate_id"
        ),
    )
    if op.get_bind().dialect.name == "postgresql":
        op.execute("""
            CREATE FUNCTION prevent_rate_line_item_mutation() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'rate_line_items are append-only';
            END;
            $$ LANGUAGE plpgsql
        """)
        op.execute("""
            CREATE TRIGGER prevent_rate_line_item_mutation
            BEFORE UPDATE OR DELETE ON rate_line_items
            FOR EACH ROW EXECUTE FUNCTION prevent_rate_line_item_mutation()
        """)
    elif op.get_bind().dialect.name == "sqlite":
        op.execute("""
            CREATE TRIGGER prevent_rate_line_item_update
            BEFORE UPDATE ON rate_line_items
            BEGIN
                SELECT RAISE(ABORT, 'rate_line_items are append-only');
            END
        """)
        op.execute("""
            CREATE TRIGGER prevent_rate_line_item_delete
            BEFORE DELETE ON rate_line_items
            BEGIN
                SELECT RAISE(ABORT, 'rate_line_items are append-only');
            END
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER prevent_rate_line_item_mutation ON rate_line_items")
        op.execute("DROP FUNCTION prevent_rate_line_item_mutation()")
    elif op.get_bind().dialect.name == "sqlite":
        op.execute("DROP TRIGGER prevent_rate_line_item_update")
        op.execute("DROP TRIGGER prevent_rate_line_item_delete")
    op.drop_table("rate_line_items")
    op.drop_table("load_versions")
    op.drop_table("load_stops")
    op.drop_table("loads")
    op.drop_table("ingestion_files")
    op.drop_table("customers")
    op.drop_table("carriers")
    op.drop_table("broker_sources")
    op.drop_table("brokers")
    # ### end Alembic commands ###
