export type Summary={id:string;name:string};
export type Carrier={id:string;name:string;mc_number?:string|null;dot_number?:string|null;phone_number?:string|null};
export type Load={id:string;display_number:string;status:string;equipment_type:string;weight_lbs?:string|null;distance_miles?:string|null;customer:Summary;source:Summary;carrier?:Carrier|null;origin?:Location|null;destination?:Location|null;next_schedule?:string|null;customer_rate?:string|null;carrier_rate?:string|null;margin?:string|null;freshness:Freshness;assignment:Assignment};
export type Location={city:string;state:string;postal_code:string};
export type Freshness={last_synced_at:string;age_seconds:number};
export type Assignment={state:string;carrier?:Carrier|null;candidate_id?:string|null;assignment_version:number;assigned_at?:string|null};
export type Detail=Load&{stops:Stop[]};
export type Stop={id:string;sequence_number:number;stop_type:string;city:string;state:string;postal_code:string;scheduled_date?:string|null;scheduled_start_at?:string|null;scheduled_end_at?:string|null;actual_arrived_at?:string|null;actual_departed_at?:string|null;location_name?:string|null};
export type Lane={broker_id:string;load_id:string;lane:{exact_key:string;metro_key?:string|null;origin:{metro_name?:string|null};destination:{metro_name?:string|null}};history:{exact_count:number;nearby_count:number;equipment_exact_count:number;equipment_nearby_count:number;selected_scope:string;data_sufficiency:string;fallback_reason?:string|null}};
export type Rate={status:string;estimate:{amount?:string|null;low?:string|null;high?:string|null;calculation_mode?:string|null};confidence:{level:string;data_sufficiency:string;reasons:string[]};population:{sample_size:number;selected_tier?:string|null;lookback_days?:number|null;source_types:string[]}};
export type Recommendation={rank:number;candidate_id:string;name:string;score:number;data_sufficiency:string;factors:{code:string;evidence_count:number;contribution:number;explanation:string}[]};
export type Recs={recommendations:Recommendation[];unscored_carriers:{candidate_id:string;name:string;reason:string}[]};
export type Candidate={candidate_id:string;name:string;mc_number?:string|null;dot_number?:string|null;carriers: (Carrier&{source_id:string;home_city?:string|null;home_state?:string|null})[]};
const base=import.meta.env.VITE_API_BASE_URL||'/api';
export async function request<T>(path:string, options?:RequestInit & {signal?:AbortSignal}):Promise<T>{const r=await fetch(`${base}${path}`,{...options,headers:options?.body?{'Content-Type':'application/json',...(options?.headers||{})}:options?.headers});if(!r.ok){let d='Request failed';try{const j=await r.json();if(typeof j.detail==='string')d=j.detail;else if(Array.isArray(j.detail))d=j.detail.map((item:unknown)=>typeof item==='object'&&item!==null&&'msg' in item?String((item as {msg:unknown}).msg):JSON.stringify(item)).join(', ');else if(j.detail!=null)d=JSON.stringify(j.detail)}catch{};throw Object.assign(new Error(d),{status:r.status})}return r.json()}
export const api={brokers:(signal?:AbortSignal)=>request<Summary[]>('/demo/brokers',{signal}),loads:(b:string,q:string,signal?:AbortSignal)=>request<{items:Load[];page:number;page_size:number;total:number}>(`/brokers/${b}/loads?${q}`,{signal}),detail:(b:string,l:string,signal?:AbortSignal)=>request<Detail>(`/brokers/${b}/loads/${l}`,{signal}),lane:(b:string,l:string,signal?:AbortSignal)=>request<Lane>(`/brokers/${b}/loads/${l}/lane-intelligence`,{signal}),rate:(b:string,l:string,signal?:AbortSignal)=>request<Rate>(`/brokers/${b}/loads/${l}/carrier-rate-estimate`,{signal}),recs:(b:string,l:string,signal?:AbortSignal)=>request<Recs>(`/brokers/${b}/loads/${l}/carrier-recommendations?limit=20`,{signal}),candidate:(b:string,c:string,signal?:AbortSignal)=>request<Candidate>(`/brokers/${b}/carrier-candidates/${encodeURIComponent(c)}`,{signal}),assign:(b:string,l:string,body:object)=>request<Assignment>(`/brokers/${b}/loads/${l}/assignments`,{method:'POST',body:JSON.stringify(body)})};
